defaults:
  - _self_
  - plannet_client_settings: prod_client
  - sauron_client_settings: prod_client
  - horizon_client_settings: dev_client

hydra:
  run:
    dir: ./output/logs/${hydra.job.name}/${now:%Y-%m-%d_%H-%M-%S}

  job_logging:
    logger: logger
